name: Test Coverage

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Measure Test Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Polaris
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
      - name: Run Tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: "--all-features --ignore-tests"
          out-type: Xml
          timeout: 240
      - name: Upload Results
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
